### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'requestDevice' on 'USB': No device selected.

### ISSUE THREAD

**Issue by icecrack3r** [GoogleChromeLabs/web-gphoto2#3]
i tried the app on the web directly, but i got an error! I using my canon 200D

> libapi.mjs:9 DOMException: Failed to execute 'open' on 'USBDevice': Access denied.
(anonymous) @ libapi.mjs:9
index.js:85 Error: I/O problem
    at throw_msg (libapi.mjs:9:18313)
    at libapi.wasm:0xe8f33
    at ret.<computed> (libapi.mjs:9:129379)
    at invoke_vi (libapi.mjs:9:195627)
    at libapi.wasm:0x10f946
    at libapi.wasm:0xe8f33
    at ret.<computed> (libapi.mjs:9:129379)
    at invoke_vi (libapi.mjs:9:195627)
    at libapi.wasm:0xe0271
    at libapi.wasm:0xe8fd8
tryToConnectToCamera @ index.js:85
DevTools failed to load source map: Could not load content for chrome-extension://hnmpcagpplmpfojmgmnngilcnanddlhb/browser-polyfill.min.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for https://unpkg.com/preact@10.6.4/dist/preact.module.js.map: System error: net::ERR_BLOCKED_BY_RESPONSE
web-gphoto2.rreverser.com/:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}

**Comment by RReverser** [comment]
Are you on Windows by any chance? If so, you'll need to override Canon's driver with generic USB driver with Zadig. Check out https://web.dev/porting-libusb-to-webusb/#important-cross-platform-compatibility-notes.

**Comment by RReverser** [comment]
Closing due to no response.
